name: flmln
publish_to: none
version: 0.0.0

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  ffi: ^2.1.4
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_lints: ^6.0.0
  ffigen: ^19.1.0

flutter:
  plugin:
    platforms:
      android:
        package: com.kekland.flmln
        pluginClass: FlMlnPlugin
        ffiPlugin: true
      ios:
        pluginClass: FlMlnPluginIOS
        ffiPlugin: true
      macos:
        pluginClass: FlMlnPluginMacOS
        ffiPlugin: true
